version: '3.7'
services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - tinyurl_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=learn_django
      - POSTGRES_PASSWORD=learn_django
      - POSTGRES_DB=learn_django_dev

volumes:
  tinyurl_data:
